#!/usr/bin/env python
from PyQt4 import QtGui
import py4circle
import py4circle.interface.FourCircleMainWindow as MainWindowFC
import sys


def main(argv):
    """
    """
    if QtGui.QApplication.instance():
        _app = QtGui.QApplication.instance()
    else:
        _app = QtGui.QApplication(sys.argv)
    return _app


if __name__ == '__main__':
    # Main application
    app = main(sys.argv)

    main_window = MainWindowFC.FourCircleMainWindow()
    main_window.show()

    app.exec_()

