#!/usr/bin/env python
import sys
import os
cwd_dir = os.getcwd()
sys.path.append(cwd_dir)

import py4circle
from py4circle.interface.gui.ipythonanalysiswidget import IPyAnalysisWidget

from PyQt5 import QtWidgets
import py4circle.interface.FourCircleMainWindow as MainWindowFC
import sys


def main(argv):
    """
    """
    if QtWidgets.QApplication.instance():
        _app = QtWidgets.QApplication.instance()
    else:
        _app = QtWidgets.QApplication(sys.argv)
    return _app


if __name__ == '__main__':
    # Main application
    app = main(sys.argv)

    main_window = MainWindowFC.FourCircleMainWindow()
    main_window.show()

    app.exec_()

